### ISSUE TITLE
Enabling a link does not save the new state on storehouse

### ISSUE THREAD

**Issue by italovalcy** [kytos/topology#119]
When you use the topology API to enable a link and restart kytos, the configuration is lost.

Steps to reproduce:
1. Start kytos `kytosd`
2. Start the network topology (e.g. `mn --topo linear,3 --controller=remote,ip=127.0.0.1,port=6653`)
3. Enable the switches/interfaces/link:
```
curl -X POST http://127.0.0.1:8181/api/kytos/topology/v3/switches/00:00:00:00:00:00:00:01/enable
curl -X POST http://127.0.0.1:8181/api/kytos/topology/v3/switches/00:00:00:00:00:00:00:02/enable
curl -X POST http://127.0.0.1:8181/api/kytos/topology/v3/switches/00:00:00:00:00:00:00:03/enable
curl -X POST http://127.0.0.1:8181/api/kytos/topology/v3/interfaces/switch/00:00:00:00:00:00:00:01/enable
curl -X POST http://127.0.0.1:8181/api/kytos/topology/v3/interfaces/switch/00:00:00:00:00:00:00:02/enable
curl -X POST http://127.0.0.1:8181/api/kytos/topology/v3/interfaces/switch/00:00:00:00:00:00:00:03/enable
curl -X POST http://127.0.0.1:8181/api/kytos/topology/v3/links/78282c4d5b579265f04ebadc4405ca1b49628eb1d684bb45e5d0607fa8b713d0/enable
```
4. Restart kytos (e.g. `kill $(cat /var/run/kytos/kytosd.pid) && sleep 5 && kytosd`)
5. Restore the topology to the latest admin config (e.g. `curl -X GET http://127.0.0.1:8181/api/kytos/topology/v3/restore`)
5. Check the status of the link (e.g. `curl -X GET http://127.0.0.1:8181/api/kytos/topology/v3/links`)

Expected behavior:
The link should remain enabled after restarting Kytos

Actual behavior:
The link gets disabled again

**Comment by cmagnobarbosa** [comment]
Related: kytos/kytos#1127
