### ISSUE TITLE
Create events to notify that Switch was enabled/disabled

### ISSUE THREAD

**Issue by josemauro** [kytos/topology#143]
Nowadays, there are NApps (of_lldp and of_l2ls) that send flows to be installed in switches without check if the switches are enabled. These NApps should only send flows to be installed in a switch if it is enabled and once the switch is disabled the installed flow should be removed. Therefore, the topology NApp should create an event to notify that a switch has been enabled and another one to notify when a switch has been disabled.
Related to:
https://github.com/kytos/of_l2ls/issues/22
https://github.com/kytos/of_lldp/pull/56

**Comment by cmagnobarbosa** [comment]
Related https://github.com/kytos/flow_manager/issues/89
