### ISSUE TITLE
Inserting interface metadata is not persistent

### ISSUE THREAD

**Issue by ArturoQuintana** [kytos/topology#158]
After testing the interface metadata persistence process, I have detected that such a process is not persistent.
To recreate this issue, it is needed to:

1. Insert a new metadata value
2. Restart the controller preserving its setting/configuration
3. Retrieve all the metadata associated with the interface targeted

**Comment by cmagnobarbosa** [comment]
Hi Arturo, thanks for reporting. Today if you enable the interface before sending the metadata to the interface, the persistence works properly. But I'm checking why this functionality is not working the same way as the persistence of metadata on switches.

**Comment by italovalcy** [comment]
@cmagnobarbosa I've tested enabling the interface before sending the metadata in two ways: using the enable_all and directly. When we use the enable_all, it also fails! Here are my tests:

1. Using enable_all=True:
```
# pkill kytosd
# rm -rf /var/tmp/kytos/
# kytosd -E
# mn --topo linear,3 --controller=remote,ip=127.0.0.1
# curl http://localhost:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1/metadata
{"metadata":{}}
# curl -X POST -d '{"bla": 10}' -H 'Content-type: application/json' http://localhost:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1/metadata
"Operation successful"
# curl http://localhost:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1/metadata
{"metadata":{"bla":10}}
# pkill kytosd
# kytosd -E
# curl http://localhost:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1/metadata
{"metadata":{}}
```
2. Enabling the interface directly:
```
# pkill kytosd
# rm -rf /var/tmp/kytos/
# kytosd
# for s in $(curl -s http://localhost:8181/api/kytos/topology/v3/switches | jq -r '.switches[].id'); do curl -X POST http://localhost:8181/api/kytos/topology/v3/switches/$s/enable; curl -X POST http://localhost:8181/api/kytos/topology/v3/interfaces/switch/$s/enable; done
# curl -X POST -d '{"bla": 10}' -H 'Content-type: application/json' http://localhost:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1/metadata
# curl http://localhost:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1/metadata
{"metadata":{"bla":10}}
# pkill kytosd
# kytosd
# curl http://localhost:8181/api/kytos/topology/v3/interfaces/00:00:00:00:00:00:00:01:1/metadata
{"metadata":{"bla":10}}
```

**Comment by cmagnobarbosa** [comment]
Hi @italovalcy, thank you very much for doing these tests. I will work to resolve this.
