### ISSUE TITLE
raised UnboundLocalError instead of KeyError

### ISSUE THREAD

**Issue by rmotitsuki** [kytos/topology#34]
I was testing the topology napp but I started my mininet incorrectly so I should receive an error.
But in this part of code I think the KeyError got silenced and I received a latter error:
```
  File "/projects/env_kytos/var/lib/kytos/napps/../napps/kytos/topology/models.py", line 312, in to_dict
    dev['custom_properties'] = cp
UnboundLocalError: local variable 'cp' referenced before assignment
```

https://github.com/kytos/topology/blob/f47c14f7ec54ec77b3edf8fa517f133e9fe5a675/models.py#L312

**Comment by rmotitsuki** [comment]
I think I´ve found the problem. The error is related to the following commit:
https://github.com/kytos/topology/commit/94a7baa015da984b3a3effb6399dc9cd8a10e24a#diff-f219bfe69e6ed201e4bdfdb371dc0c9b

```
-                custom = self._custom_properties[device.id]
 +                cp = self._custom_properties[device.id]

```
_**custom**_ was renamed to _**cp**_ but the old variable name stayed here in this part of code:
```
             except KeyError:
                  custom = {}
```

**Comment by beraldoleal** [comment]
@macartur @renanrodrigo please, can you guys take a look on this?
