### ISSUE TITLE
Add support for metadata

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/topology#38]
As described in the [Topology Improvement Blueprint](https://github.com/kytos/kytos/blob/master/docs/blueprints/EP013.rst)

**Comment by renanrodrigo** [comment]
This may include https://github.com/kytos/topology/issues/35

**Comment by beraldoleal** [comment]
Basic metadata to Switch and Interface main entities is ready. We need to do a small refactor on Link entity to make sure that is in order with our last discussions.
