### ISSUE TITLE
Generate events when any metadata is updated

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/topology#43]
This is needed for new metadata, deleted metadata or updated metadata.
All entities must be included.

**Comment by hdiogenes** [comment]
I think it would be a good idea to document why this is needed (updating the UI?). Also: do we really need three separate events? Wouldn't a single `metadata.updated` event with the new metadata content be enough?

**Comment by beraldoleal** [comment]
@macartur is already implementing this. with separated events in order to make it easy to user developers.
